### ISSUE TITLE
Tries to load 3 files from the visited domain on every page load

### ISSUE THREAD

**Issue by supersoju** [powerpak/hn-sidebar#2]
The plugin tries to load some news.ycombinator.com resources (s.gif, y18.gif and grayarrow.gif) from the viewed page's domain if the page doesn't have a HN discussion.

These can be viewed when looking in the Chrome JS console.

Example:
http://www.google.com/randompage
Has 3 404 errors in the console
https://www.google.com/
no errors

**Comment by powerpak** [comment]
You're right, it was because HN's HTML was getting parsed by jQuery and instantiating the elements must have fetched the <img> URL's.  Pushed a fix.
